name: gendiff

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
        uses: qltysh/qlty-action/coverage@main
        with:
        env: { { secrets.QLTY_COVERAGE_TOKEN } }
        files: coverage/lcov.info
